CREATE TABLE USERS(
    username        VARCHAR(15),
    password        VARCHAR(300),
    display_name    VARCHAR(50),
    UNIQUE KEY unique_username(username),
    sunday          VARCHAR(96),
    monday          VARCHAR(96),
    tuesday         VARCHAR(96),
    wednesday       VARCHAR(96),
    thursday        VARCHAR(96),
    friday          VARCHAR(96),
    saturday        VARCHAR(96),
    g0membership    VARCHAR(100),
    g1membership    VARCHAR(100),
    g2membership    VARCHAR(100),
    g3membership    VARCHAR(100),
    g4membership    VARCHAR(100),
    g5membership    VARCHAR(100),
    email           VARCHAR(100),
    lastlogin       INT,
    PRIMARY KEY(username));
